export const categoryWiseImages = {
  "living-room": [
    "/Melange_Faridabad1_1.jpg",
    "/Melange_Faridabad1_2.jpg",
    "/Melange_Faridabad1_3.jpg",
    "/Melange_Faridabad1_4.jpg",
    "/Melange_Faridabad1_5.jpg",
    "/Melange_Faridabad2_4.jpg",
    "/Melange_Faridabad2_5.jpg",
    "/Melange_Faridabad4_1.jpg",
    "/Melange_Faridabad4_2.jpg",
    "/Melange_Faridabad4_3.jpg",
    "/Melange_Faridabad4_4.jpg",
    "/SashiAggarwal1_1.jpg",
    "/SashiAggarwal1_2.jpg",
    "/SashiAggarwal1_3.jpg",
    "/SashiAggarwal1_4.jpg",
    "/SashiAggarwal1_5.jpg",
    "/SashiAggarwal2_1.jpg",
    "/SashiAggarwal2_2.jpg",
    "/SashiAggarwal2_3.jpg",
    "/SashiAggarwal2_4.jpg",
    "/SashiAggarwal2_5.jpg",
    "/adarsh_aggarwal1_1.jpg",
    "/adarsh_aggarwal1_2.jpg",
    "/adarsh_aggarwal1_3.jpg",
    "/adarsh_aggarwal1_4.jpg",
    "/adarsh_aggarwal1_5.jpg",
    "/AshishGupta1_3.jpg",
    "/AshishGupta2_1.jpg",
    "/AshishGupta2_2.jpg",
    "/AshishGupta2_3.jpg",
    "/AshishGupta2_4.jpg",
    "/AshishGupta2_5.jpg",
    "/Praveen_Nangia1_5.jpg",
    "/Praveen_Nangia2_1.jpg",
    "/Praveen_Nangia2_2.jpg",
    "/Praveen_Nangia2_3.jpg",
    "/Praveen_Nangia2_4.jpg",
    "/Praveen_Nangia2_5.jpg",
    "/Deepali1_1.jpg",
    "/Deepali1_2.jpg",
    "/Deepali1_3.jpg",
    "/Deepali1_4.jpg",
    "/Deepali1_5.jpg",
    "/Deepali2_1.jpg",
    "/Deepali2_2.jpg",
    "/Deepali2_3.jpg",
    "/Deepali2_4.jpg",
    "/Deepali2_5.jpg",
    "/Deepali4_1.jpg",
    "/Deepali4_2.jpg",
    "/Deepali4_3.jpg",
    "/Deepali4_4.jpg",
    "/Deepali4_5.jpg",
    "/Sec_15_Noida_1_1.jpg",
    "/Sec_15_Noida_1_2.jpg",
    "/Sec_15_Noida_1_3.jpg",
    "/Sec_15_Noida_1_4.jpg",
    "/Sec_15_Noida_1_5.jpg",
    "/Sec_15_Noida_4_2.jpg",
    "/Sec_15_Noida_4_3.jpg",
    "/Sec_15_Noida_4_4.jpg",
    "/Sec_15_Noida_4_5.jpg",
    "/bhuvam13.jpg",
    "/bhuvam14.jpg",
    "/bhuvam21.jpg",
    "/bhuvam22.jpg",
    "/bhuvam23.jpg",
    "/bhuvam24.jpg",
  ],
  "dining-area": [
    "/Melange_Faridabad2_1.jpg",
    "/Melange_Faridabad2_2.jpg",
    "/Melange_Faridabad2_3.jpg",
    "/Melange_Faridabad4_5.jpg",
    "/AshishGupta2_2.jpg",
    "/AshishGupta2_4.jpg",
    "/Sec_15_Noida_4_1.jpg",
    "/bhuvam11.jpg",
    "/bhuvam12.jpg",
  ],
  bedroom: [
    "/Melange_Faridabad3_1.jpg",
    "/Melange_Faridabad3_2.jpg",
    "/Melange_Faridabad3_3.jpg",
    "/Melange_Faridabad3_4.jpg",
    "/SashiAggarwal3_1.jpg",
    "/SashiAggarwal3_2.jpg",
    "/SashiAggarwal3_3.jpg",
    "/SashiAggarwal3_4.jpg",
    "/SashiAggarwal3_5.jpg",
    "/Praveen_Nangia1_1.jpg",
    "/Praveen_Nangia1_2.jpg",
    "/Praveen_Nangia1_3.jpg",
    "/Praveen_Nangia1_4.jpg",
    "/adarsh_aggarwal2_1.jpg",
    "/adarsh_aggarwal2_2.jpg",
    "/adarsh_aggarwal2_3.jpg",
    "/adarsh_aggarwal2_4.jpg",
    "/adarsh_aggarwal2_5.jpg",
    "/adarsh_aggarwal4_1.jpg",
    "/adarsh_aggarwal4_2.jpg",
    "/adarsh_aggarwal4_3.jpg",
    "/adarsh_aggarwal4_4.jpg",
    "/adarsh_aggarwal4_5.jpg",
    "/Deepali3_1.jpg",
    "/Deepali3_2.jpg",
    "/Deepali3_3.jpg",
    "/Deepali3_4.jpg",
    "/Deepali3_5.jpg",
    "/Sec_15_Noida_3_1.jpg",
    "/Sec_15_Noida_3_2.jpg",
    "/Sec_15_Noida_3_3.jpg",
    "/Sec_15_Noida_3_4.jpg",
    "/Sec_15_Noida_3_5.jpg",
    "/bhuvam31.jpg",
    "/bhuvam32.jpg",
    "/bhuvam33.jpg",
    "/bhuvam34.jpg",
  ],
  tvCabinet: ["/SashiAggarwal4_1.jpg", "/SashiAggarwal4_2.jpg"],
  closets: [
    "/SashiAggarwal4_3.jpg",
    "/SashiAggarwal4_4.jpg",
    "/SashiAggarwal4_5.jpg",
  ],
  kitchen: [],
  bathroom: [
    "/bhuvam42.jpg",
    "/bhuvam43.jpg",
    "/bhuvam44.jpg",
    "/bhuvam45.jpg",
    "/bhuvam51.jpg",
    "/bhuvam52.jpg",
    "/bhuvam53.jpg",
    "/bhuvam54.jpg",
    "/bhuvam55.jpg",
    "/bhuvam15.jpg",
  ],
  "outdoor-space": [
    "/Sec_15_Noida_2_1.jpg",
    "/Sec_15_Noida_2_2.jpg",
    "/Sec_15_Noida_2_3.jpg",
    "/Sec_15_Noida_2_4.jpg",
    "/Sec_15_Noida_2_5.jpg",
  ],
  "home-office": [],
  entryway: [],
  other: [],
};

export const categories = [
  "living-room",
  "dining-area",
  "bedroom",
  "tvCabinet",
  "closets",
  // "kitchen",
  "bathroom",
  "outdoor-space",
  // "home-office",
  // "entryway",
  // "other",
];
